### ISSUE TITLE
Nefunkční rodičovský PIN

### ISSUE THREAD

**Issue by Vasek79** [rossowl/stvh#1]
Kanály "pro dospělé" zůstavají zamknuté - ukazuje se smyčka s požadavkem na odemknutí. Pin mám zadaný a mám ho správně - u krejcirova řešení i na webu funguje.
S původními chybami v readme jsem si poradil, ale tady nevím. 
Zarazilo mě, že na 110 řádku je "pin=None", ale třeba je to správně.

**Comment by rossowl** [comment]
pin opraven: https://github.com/rossowl/stvh/commit/0e79dec07db15412e1200c724aceff56a78578e1
spatne upravena zkopirovana URL, 18+ jsem nezkousel
cely soubor: https://github.com/rossowl/stvh/blob/master/sledovanitv.py
readme chyby by mely byt opravene uz vcera, jednalo se o preklepy v nazvu souboru sledovani.tv -> sledovanitv.py
na radku 110 je vychozi hodnota, pin je nepovinny parametr

**Comment by rossowl** [comment]
Po  výměně souboru .py buď počkejte hodinu na obnovení cache nebo vymažte všechny soubory v .cache. Pokud chcete mít i ikonu kanálu bez zámku, vygenerujte znovu playlist, přinuťte tvheadend, aby ho znovu načetl, potom vymažte kanály 18+ a znovu je namapujte ze Services, pak už budou s normální ikonou.

**Comment by rossowl** [comment]
nastaveni jsem presunul do zvlastniho souboru, at se skript nemusi po kazde zmene upravovat. Nastavte si sledovanitv_settings.py (staci zkopirovat z puvodniho .py souboru, nic se nezmenilo) a potom jen muzete menit sledovanitv.py beze zmen a nastavovani.
https://github.com/rossowl/stvh/commit/464de53e5db60b37d2793e5e9a7517687707ae64

**Comment by Vasek79** [comment]
Funguje výborně. Díky.
