### ISSUE TITLE
XMLTV nejde zprovoznit nc

### ISSUE THREAD

**Issue by Vasek79** [rossowl/stvh#2]
Dobrý den,

předem díky za STVH. Vše, až na xmltv fujnguje, když ale zadám "cat /home/hts/.xmltv/xmltv.xml | nc -w 5 -U /home/hts/.hts/tvheadend/epggrab/xmltv.sock" , vráti mi "nc: unix connect failed: No such file or directory". Nemám s tímto vůbec žádné zkušenosti.

Díky Vašek

**Comment by rossowl** [comment]
Máte povolený Externí XMLTV grabber v TVHeadEndu? 
Konfigurace -> Program / EPG -> Moduly EPG Grabberů
Externí EPG musí svítit zeleně. Pokud ne, povolte ho.
Tím by se měl vytvořit ten socket a vy do něho můžete tím příkazem zapisovat data.

**Comment by Vasek79** [comment]
Je povolený, ale xmltv.sock v **/home/hts/.hts/tvheadend/epggrab/xmltv.sock** nevidím - nevytvořil se.
U Externího EPG je **Path: /var/lib/hts/.hts/tvheadend/epggrab/xmltv.sock**, ale v příkazu v manuálu je: **/home/hts/.hts/tvheadend/epggrab/xmltv.sock**. Je to v pořádku?

**Comment by Vasek79** [comment]
No, už jsem zkusil nahradit cestu v příkazu z návodu cestou z tvheadendu u externího EPG a zdá se že funguje.

**Comment by rossowl** [comment]
Máme asi každý jinou verzi. Vy máte home uživatele hts ve /var/lib/hts, já na raspbianu do /home/hts
Přeji hezké užívání.

**Comment by Vasek79** [comment]
Tak to bude ono. Já to mám na Armbianu. Hw je totiž Banana pi.Odesláno z mého chytrého telefonu Samsung Galaxy.
-------- Původní zpráva --------Od: rossowl <notifications@github.com> Datum: 28.08.20  10:25  (GMT+01:00) Komu: rossowl/stvh <stvh@noreply.github.com> Cc: Vasek79 <vasa79burian@gmail.com>, Author <author@noreply.github.com> Předmět: Re: [rossowl/stvh] XMLTV nejde zprovoznit nc (#2) 

Máme asi každý jinou verzi. Vy máte home uživatele hts ve /var/lib/hts, já na raspbianu do /home/hts

Přeji hezké užívání.
